detection:
  input_traffic_video_path: "traffic-videos/test-video.mp4"
  output_folder_name: "output"
  mask_image_path: "masks/test-video_mask.jpg"
  confirmation_frame: 15
  confidence_threshold: 0.35
  yolo_model:
    yolo_model_path: "models/VehicleDetectionYolov11LModel.pt"

traffic_signal_allocator:
  traffic_intersection_data_path: "traffic_data/intersection_data.json"
  base_green_time: 5
  max_green_time: 60
  yellow_time: 3
  total_cycle_time: 120
